---
apiVersion: v1
kind: Namespace
metadata: 
  name: codeserver

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: codeserver
  name: codeserver-configmap
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-146.190.194.33.nip.io


 