---
apiVersion: v1
kind: Namespace
metadata: 
  name: bggns

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bggns
  name: bgg-configmap
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

 