
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bggdb-deploy
    name: bggdb-deploy

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bggdb-po
  template:
    metadata: 
      name: bggdb-po
      namespace: bggns
      labels:
        version: v1
        app: bggdb-po
    spec:
      containers:
        - name: bggdb-po
          image: stackupiss/bgg-database:v1
          ports:
            - name: db-port
              containerPort: 3306         
    

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns  
spec:
  type: ClusterIP
  selector:
    app: bggdb-po
  ports:
    - port: 3306
      targetPort: 3306