---
apiVersion: v1
kind: Namespace
metadata: 
  name: minions

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: minions
  name: minio-configmap
data:
  MINIO_ROOT_USER: minioadmin
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...3}.minio-headless-svc.minions.svc.cluster.local/data
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"


 